// Generated by scripts/generate_cratesio_tokens.py; source review required.
use crate::catalog::schema::Node;
pub(super) const FIND_API_TOKEN: usize = 16;
#[rustfmt::skip]
pub(super) const NODES: &[Node] = &[
    Node::Text,
    Node::Array(0),
    Node::Nullable(1),
    Node::Timestamp,
    Node::Enum(&["publish-new","publish-update","trusted-publishing","yank","change-owners"]),
    Node::Array(4),
    Node::Nullable(5),
    Node::Timestamp,
    Node::Nullable(7),
    Node::Integer(2147483647),
    Node::Timestamp,
    Node::Nullable(10),
    Node::Text,
    Node::Any,
    Node::Object(&[("crate_scopes", 2, true),("created_at", 3, true),("endpoint_scopes", 6, true),("expired_at", 8, true),("id", 9, true),("last_used_at", 11, true),("name", 12, true)], Some(13)),
    Node::Any,
    Node::Object(&[("api_token", 14, true)], Some(15)),
];
