//! Generated exhaustive active-operation associations.
//!
//! Regenerate with `scripts/generate_operation_associations.py`.

use cloud_sdk::{ServiceMarker, operation_id};

use super::OperationBindingEvidence;
use super::policy::{
    HetznerOperation, OperationDescriptor, ReadOnlyOperation, ResponseIdentityClass, Sealed,
};
use super::types::*;
use crate::identity::{CloudService, DnsService, SecurityService, StorageService};

macro_rules! body_headers {
    (BodyForbidden) => {
        AcceptJson
    };
    (JsonBody) => {
        AcceptAndContentTypeJson
    };
}
macro_rules! body_media {
    (BodyForbidden) => {
        NoRequestMedia
    };
    (JsonBody) => {
        JsonRequestMedia
    };
}
macro_rules! success_body {
    (EmptyResponse) => {
        EmptySuccessBody
    };
    ($response:ident) => {
        JsonSuccessBody
    };
}
macro_rules! success_media {
    (EmptyResponse) => {
        ForbiddenSuccessMedia
    };
    ($response:ident) => {
        JsonSuccessMedia
    };
}

macro_rules! read_only_operation {
    ($marker:ident, NoPermit) => {
        impl ReadOnlyOperation for $marker {}
    };
    ($marker:ident, $permit:ident) => {};
}

macro_rules! operation_associations {
    ($(($marker:ident, $id:literal, $service:ident, $endpoint:ident, $authentication:ident,
        $method:ident, $query:ident, $body:ident, $status:ident, $response:ident,
        $path:literal, $success_root:literal, $success_required:literal, $response_identity:expr,
        $pagination:ident, $retry:ident, $permit:ident),)+) => {
        /// Sealed markers for every active source-locked Hetzner operation.
        pub mod operations {
            use super::*;
            $(
                #[doc = concat!("Association for Hetzner operation `", $id, "`.")]
                #[derive(Clone, Copy, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
                pub struct $marker;
                impl Sealed for $marker {}
                impl HetznerOperation for $marker {
                    type Service = $service;
                    type EndpointPolicy = $endpoint;
                    type Authentication = $authentication;
                    type AuthenticationScope = RequiredServiceScope;
                    type Query = $query;
                    type Body = $body;
                    type RequestHeaders = body_headers!($body);
                    type RequestMedia = body_media!($body);
                    type SuccessStatus = $status;
                    type SuccessBody = success_body!($response);
                    type SuccessMedia = success_media!($response);
                    type ErrorBody = JsonErrorBody;
                    type ErrorMedia = JsonErrorMedia;
                    type ResponseCaps = JsonResponseCaps;
                    type Pagination = $pagination;
                    type Quota = HetznerQuota;
                    type Retry = $retry;
                    type Streaming = BufferedStreaming;
                    type Success = $response;
                    type Error = HetznerErrorResponse;
                    type Permit = $permit;
                    const DESCRIPTOR: OperationDescriptor = OperationDescriptor::new(
                        operation_id!($id),
                        <$service as ServiceMarker>::ID,
                        <$endpoint as EndpointAssociation>::BASE,
                        <$authentication as AuthenticationAssociation>::CLASS,
                        <$method as MethodAssociation>::METHOD,
                        <$query as QueryAssociation>::POLICY,
                        <$body as BodyAssociation>::POLICY,
                        <$status as StatusAssociation>::STATUS,
                        <$response as ResponseAssociation>::SHAPE,
                        $path,
                        $success_root,
                        $success_required,
                        $response_identity,
                        <$pagination as PaginationAssociation>::POLICY,
                        <$retry as RetryAssociation>::POLICY,
                        <$permit as PermitAssociation>::CLASS,
                    );
                }
                read_only_operation!($marker, $permit);
            )+
        }

        /// Descriptors for all active operations in stable operation-ID order.
        pub const ALL_OPERATIONS: &[OperationDescriptor] = &[
            $(<operations::$marker as HetznerOperation>::DESCRIPTOR,)+
        ];

        /// Marker-derived evidence for all active operations in stable order.
        #[doc(hidden)]
        pub const ALL_OPERATION_EVIDENCE: &[OperationBindingEvidence] = &[
            $(OperationBindingEvidence::of::<operations::$marker>(),)+
        ];

        pub(crate) fn operation_path_template(operation_id: &str) -> Option<&'static str> {
            match operation_id {
                $($id => Some($path),)+
                _ => None,
            }
        }
    };
}

#[rustfmt::skip]
operation_associations!(
        (AddLoadBalancerService, "add_load_balancer_service", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/load_balancers/{id}/actions/add_service", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (AddLoadBalancerTarget, "add_load_balancer_target", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/load_balancers/{id}/actions/add_target", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (AddNetworkRoute, "add_network_route", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/networks/{id}/actions/add_route", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (AddNetworkSubnet, "add_network_subnet", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/networks/{id}/actions/add_subnet", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (AddServerToPlacementGroup, "add_server_to_placement_group", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/servers/{id}/actions/add_to_placement_group", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (AddZoneRrsetRecords, "add_zone_rrset_records", DnsService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/zones/{id_or_name}/rrsets/{rr_name}/{rr_type}/actions/add_records", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (ApplyFirewallToResources, "apply_firewall_to_resources", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionsResponse, "/firewalls/{id}/actions/apply_to_resources", "-", "actions", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (AssignFloatingIp, "assign_floating_ip", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/floating_ips/{id}/actions/assign", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (AssignPrimaryIp, "assign_primary_ip", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/primary_ips/{id}/actions/assign", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (AttachLoadBalancerToNetwork, "attach_load_balancer_to_network", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/load_balancers/{id}/actions/attach_to_network", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (AttachServerIso, "attach_server_iso", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/servers/{id}/actions/attach_iso", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (AttachServerToNetwork, "attach_server_to_network", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/servers/{id}/actions/attach_to_network", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (AttachVolume, "attach_volume", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/volumes/{id}/actions/attach", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (ChangeFloatingIpDnsPtr, "change_floating_ip_dns_ptr", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/floating_ips/{id}/actions/change_dns_ptr", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (ChangeFloatingIpProtection, "change_floating_ip_protection", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/floating_ips/{id}/actions/change_protection", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (ChangeImageProtection, "change_image_protection", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/images/{id}/actions/change_protection", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (ChangeLoadBalancerAlgorithm, "change_load_balancer_algorithm", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/load_balancers/{id}/actions/change_algorithm", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (ChangeLoadBalancerDnsPtr, "change_load_balancer_dns_ptr", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/load_balancers/{id}/actions/change_dns_ptr", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (ChangeLoadBalancerProtection, "change_load_balancer_protection", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/load_balancers/{id}/actions/change_protection", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (ChangeLoadBalancerType, "change_load_balancer_type", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/load_balancers/{id}/actions/change_type", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, CostPermit),
        (ChangeNetworkIpRange, "change_network_ip_range", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/networks/{id}/actions/change_ip_range", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (ChangeNetworkProtection, "change_network_protection", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/networks/{id}/actions/change_protection", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (ChangePrimaryIpDnsPtr, "change_primary_ip_dns_ptr", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/primary_ips/{id}/actions/change_dns_ptr", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (ChangePrimaryIpProtection, "change_primary_ip_protection", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/primary_ips/{id}/actions/change_protection", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (ChangeServerAliasIps, "change_server_alias_ips", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/servers/{id}/actions/change_alias_ips", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (ChangeServerDnsPtr, "change_server_dns_ptr", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/servers/{id}/actions/change_dns_ptr", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (ChangeServerProtection, "change_server_protection", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/servers/{id}/actions/change_protection", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (ChangeServerType, "change_server_type", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/servers/{id}/actions/change_type", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, CostPermit),
        (ChangeStorageBoxProtection, "change_storage_box_protection", StorageService, StorageEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/storage_boxes/{id}/actions/change_protection", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (ChangeStorageBoxSubaccountHomeDirectory, "change_storage_box_subaccount_home_directory", StorageService, StorageEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/storage_boxes/{id}/subaccounts/{subaccount_id}/actions/change_home_directory", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (ChangeStorageBoxType, "change_storage_box_type", StorageService, StorageEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/storage_boxes/{id}/actions/change_type", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, CostPermit),
        (ChangeVolumeProtection, "change_volume_protection", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/volumes/{id}/actions/change_protection", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (ChangeZonePrimaryNameservers, "change_zone_primary_nameservers", DnsService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/zones/{id_or_name}/actions/change_primary_nameservers", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (ChangeZoneProtection, "change_zone_protection", DnsService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/zones/{id_or_name}/actions/change_protection", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (ChangeZoneRrsetProtection, "change_zone_rrset_protection", DnsService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/zones/{id_or_name}/rrsets/{rr_name}/{rr_type}/actions/change_protection", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (ChangeZoneRrsetTtl, "change_zone_rrset_ttl", DnsService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/zones/{id_or_name}/rrsets/{rr_name}/{rr_type}/actions/change_ttl", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (ChangeZoneTtl, "change_zone_ttl", DnsService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/zones/{id_or_name}/actions/change_ttl", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (CreateCertificate, "create_certificate", SecurityService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, CompositeResponse, "/certificates", "certificate", "certificate", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (CreateFirewall, "create_firewall", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, CompositeResponse, "/firewalls", "firewall", "-", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (CreateFloatingIp, "create_floating_ip", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, CompositeResponse, "/floating_ips", "floating_ip", "floating_ip", ResponseIdentityClass::None, NoPagination, NeverRetry, CostPermit),
        (CreateLoadBalancer, "create_load_balancer", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, CompositeResponse, "/load_balancers", "load_balancer", "action,load_balancer", ResponseIdentityClass::None, NoPagination, NeverRetry, CostPermit),
        (CreateNetwork, "create_network", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ResourceResponse, "/networks", "network", "-", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (CreatePlacementGroup, "create_placement_group", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, CompositeResponse, "/placement_groups", "placement_group", "placement_group", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (CreatePrimaryIp, "create_primary_ip", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, CompositeResponse, "/primary_ips", "primary_ip", "primary_ip", ResponseIdentityClass::None, NoPagination, NeverRetry, CostPermit),
        (CreateServer, "create_server", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, CompositeResponse, "/servers", "server", "action,next_actions,root_password,server", ResponseIdentityClass::None, NoPagination, NeverRetry, CostPermit),
        (CreateServerImage, "create_server_image", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, CompositeResponse, "/servers/{id}/actions/create_image", "image", "-", ResponseIdentityClass::None, NoPagination, NeverRetry, CostPermit),
        (CreateSshKey, "create_ssh_key", SecurityService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ResourceResponse, "/ssh_keys", "ssh_key", "ssh_key", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (CreateStorageBox, "create_storage_box", StorageService, StorageEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, CompositeResponse, "/storage_boxes", "storage_box", "action,storage_box", ResponseIdentityClass::None, NoPagination, NeverRetry, CostPermit),
        (CreateStorageBoxSnapshot, "create_storage_box_snapshot", StorageService, StorageEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, CompositeResponse, "/storage_boxes/{id}/snapshots", "snapshot", "action,snapshot", ResponseIdentityClass::ParentResource, NoPagination, NeverRetry, MutationPermit),
        (CreateStorageBoxSubaccount, "create_storage_box_subaccount", StorageService, StorageEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, CompositeResponse, "/storage_boxes/{id}/subaccounts", "subaccount", "action,subaccount", ResponseIdentityClass::ParentResource, NoPagination, NeverRetry, MutationPermit),
        (CreateVolume, "create_volume", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, CompositeResponse, "/volumes", "volume", "action,next_actions,volume", ResponseIdentityClass::None, NoPagination, NeverRetry, CostPermit),
        (CreateZone, "create_zone", DnsService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, CompositeResponse, "/zones", "zone", "action,zone", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (CreateZoneRrset, "create_zone_rrset", DnsService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, CompositeResponse, "/zones/{id_or_name}/rrsets", "rrset", "action,rrset", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (DeleteCertificate, "delete_certificate", SecurityService, CloudEndpointPolicy, BearerAuthentication, DeleteMethod, QueryForbidden, BodyForbidden, StatusNoContent, EmptyResponse, "/certificates/{id}", "-", "-", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (DeleteFirewall, "delete_firewall", CloudService, CloudEndpointPolicy, BearerAuthentication, DeleteMethod, QueryForbidden, BodyForbidden, StatusNoContent, EmptyResponse, "/firewalls/{id}", "-", "-", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (DeleteFloatingIp, "delete_floating_ip", CloudService, CloudEndpointPolicy, BearerAuthentication, DeleteMethod, QueryForbidden, BodyForbidden, StatusNoContent, EmptyResponse, "/floating_ips/{id}", "-", "-", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (DeleteImage, "delete_image", CloudService, CloudEndpointPolicy, BearerAuthentication, DeleteMethod, QueryForbidden, BodyForbidden, StatusNoContent, EmptyResponse, "/images/{id}", "-", "-", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (DeleteLoadBalancer, "delete_load_balancer", CloudService, CloudEndpointPolicy, BearerAuthentication, DeleteMethod, QueryForbidden, BodyForbidden, StatusNoContent, EmptyResponse, "/load_balancers/{id}", "-", "-", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (DeleteLoadBalancerService, "delete_load_balancer_service", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/load_balancers/{id}/actions/delete_service", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (DeleteNetwork, "delete_network", CloudService, CloudEndpointPolicy, BearerAuthentication, DeleteMethod, QueryForbidden, BodyForbidden, StatusNoContent, EmptyResponse, "/networks/{id}", "-", "-", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (DeleteNetworkRoute, "delete_network_route", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/networks/{id}/actions/delete_route", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (DeleteNetworkSubnet, "delete_network_subnet", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/networks/{id}/actions/delete_subnet", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (DeletePlacementGroup, "delete_placement_group", CloudService, CloudEndpointPolicy, BearerAuthentication, DeleteMethod, QueryForbidden, BodyForbidden, StatusNoContent, EmptyResponse, "/placement_groups/{id}", "-", "-", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (DeletePrimaryIp, "delete_primary_ip", CloudService, CloudEndpointPolicy, BearerAuthentication, DeleteMethod, QueryForbidden, BodyForbidden, StatusNoContent, EmptyResponse, "/primary_ips/{id}", "-", "-", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (DeleteServer, "delete_server", CloudService, CloudEndpointPolicy, BearerAuthentication, DeleteMethod, QueryForbidden, BodyForbidden, StatusOk, ActionResponse, "/servers/{id}", "-", "-", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (DeleteSshKey, "delete_ssh_key", SecurityService, CloudEndpointPolicy, BearerAuthentication, DeleteMethod, QueryForbidden, BodyForbidden, StatusNoContent, EmptyResponse, "/ssh_keys/{id}", "-", "-", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (DeleteStorageBox, "delete_storage_box", StorageService, StorageEndpointPolicy, BearerAuthentication, DeleteMethod, QueryForbidden, BodyForbidden, StatusCreated, ActionResponse, "/storage_boxes/{id}", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (DeleteStorageBoxSnapshot, "delete_storage_box_snapshot", StorageService, StorageEndpointPolicy, BearerAuthentication, DeleteMethod, QueryForbidden, BodyForbidden, StatusCreated, ActionResponse, "/storage_boxes/{id}/snapshots/{snapshot_id}", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (DeleteStorageBoxSubaccount, "delete_storage_box_subaccount", StorageService, StorageEndpointPolicy, BearerAuthentication, DeleteMethod, QueryForbidden, BodyForbidden, StatusCreated, ActionResponse, "/storage_boxes/{id}/subaccounts/{subaccount_id}", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (DeleteVolume, "delete_volume", CloudService, CloudEndpointPolicy, BearerAuthentication, DeleteMethod, QueryForbidden, BodyForbidden, StatusNoContent, EmptyResponse, "/volumes/{id}", "-", "-", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (DeleteZone, "delete_zone", DnsService, CloudEndpointPolicy, BearerAuthentication, DeleteMethod, QueryForbidden, BodyForbidden, StatusCreated, ActionResponse, "/zones/{id_or_name}", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (DeleteZoneRrset, "delete_zone_rrset", DnsService, CloudEndpointPolicy, BearerAuthentication, DeleteMethod, QueryForbidden, BodyForbidden, StatusCreated, ActionResponse, "/zones/{id_or_name}/rrsets/{rr_name}/{rr_type}", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (DetachLoadBalancerFromNetwork, "detach_load_balancer_from_network", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/load_balancers/{id}/actions/detach_from_network", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (DetachServerFromNetwork, "detach_server_from_network", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/servers/{id}/actions/detach_from_network", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (DetachServerIso, "detach_server_iso", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, BodyForbidden, StatusCreated, ActionResponse, "/servers/{id}/actions/detach_iso", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (DetachVolume, "detach_volume", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, BodyForbidden, StatusCreated, ActionResponse, "/volumes/{id}/actions/detach", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (DisableLoadBalancerPublicInterface, "disable_load_balancer_public_interface", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, BodyForbidden, StatusCreated, ActionResponse, "/load_balancers/{id}/actions/disable_public_interface", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (DisableServerBackup, "disable_server_backup", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, BodyForbidden, StatusCreated, ActionResponse, "/servers/{id}/actions/disable_backup", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (DisableServerRescue, "disable_server_rescue", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, BodyForbidden, StatusCreated, ActionResponse, "/servers/{id}/actions/disable_rescue", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (DisableStorageBoxSnapshotPlan, "disable_storage_box_snapshot_plan", StorageService, StorageEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, BodyForbidden, StatusCreated, ActionResponse, "/storage_boxes/{id}/actions/disable_snapshot_plan", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (EnableLoadBalancerPublicInterface, "enable_load_balancer_public_interface", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, BodyForbidden, StatusCreated, ActionResponse, "/load_balancers/{id}/actions/enable_public_interface", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (EnableServerBackup, "enable_server_backup", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, BodyForbidden, StatusCreated, ActionResponse, "/servers/{id}/actions/enable_backup", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, CostPermit),
        (EnableServerRescue, "enable_server_rescue", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, CompositeResponse, "/servers/{id}/actions/enable_rescue", "-", "-", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (EnableStorageBoxSnapshotPlan, "enable_storage_box_snapshot_plan", StorageService, StorageEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/storage_boxes/{id}/actions/enable_snapshot_plan", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (GetAction, "get_action", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ActionResponse, "/actions/{id}", "-", "action", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetActions, "get_actions", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, RequiredQuery, BodyForbidden, StatusOk, ActionsResponse, "/actions", "-", "actions", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetCertificate, "get_certificate", SecurityService, CloudEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ResourceResponse, "/certificates/{id}", "certificate", "certificate", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetCertificatesAction, "get_certificates_action", SecurityService, CloudEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ActionResponse, "/certificates/actions/{id}", "-", "action", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetFirewall, "get_firewall", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ResourceResponse, "/firewalls/{id}", "firewall", "firewall", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetFirewallsAction, "get_firewalls_action", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ActionResponse, "/firewalls/actions/{id}", "-", "action", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetFloatingIp, "get_floating_ip", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ResourceResponse, "/floating_ips/{id}", "floating_ip", "floating_ip", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetFloatingIpsAction, "get_floating_ips_action", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ActionResponse, "/floating_ips/actions/{id}", "-", "action", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetImage, "get_image", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ResourceResponse, "/images/{id}", "image", "-", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetImagesAction, "get_images_action", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ActionResponse, "/images/actions/{id}", "-", "action", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetIso, "get_iso", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ResourceResponse, "/isos/{id}", "iso", "iso", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetLoadBalancer, "get_load_balancer", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ResourceResponse, "/load_balancers/{id}", "load_balancer", "load_balancer", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetLoadBalancerMetrics, "get_load_balancer_metrics", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, RequiredQuery, BodyForbidden, StatusOk, MetricsResponse, "/load_balancers/{id}/metrics", "-", "metrics", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetLoadBalancerType, "get_load_balancer_type", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ResourceResponse, "/load_balancer_types/{id}", "load_balancer_type", "load_balancer_type", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetLoadBalancersAction, "get_load_balancers_action", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ActionResponse, "/load_balancers/actions/{id}", "-", "action", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetLocation, "get_location", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ResourceResponse, "/locations/{id}", "location", "location", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetNetwork, "get_network", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ResourceResponse, "/networks/{id}", "network", "-", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetNetworksAction, "get_networks_action", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ActionResponse, "/networks/actions/{id}", "-", "action", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetPlacementGroup, "get_placement_group", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ResourceResponse, "/placement_groups/{id}", "placement_group", "placement_group", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetPricing, "get_pricing", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, PricingResponse, "/pricing", "-", "pricing", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetPrimaryIp, "get_primary_ip", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ResourceResponse, "/primary_ips/{id}", "primary_ip", "primary_ip", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetPrimaryIpsAction, "get_primary_ips_action", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ActionResponse, "/primary_ips/actions/{id}", "-", "action", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetServer, "get_server", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ResourceResponse, "/servers/{id}", "server", "-", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetServerMetrics, "get_server_metrics", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, RequiredQuery, BodyForbidden, StatusOk, MetricsResponse, "/servers/{id}/metrics", "-", "metrics", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetServerType, "get_server_type", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ResourceResponse, "/server_types/{id}", "server_type", "server_type", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetServersAction, "get_servers_action", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ActionResponse, "/servers/actions/{id}", "-", "action", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetSshKey, "get_ssh_key", SecurityService, CloudEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ResourceResponse, "/ssh_keys/{id}", "ssh_key", "ssh_key", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetStorageBox, "get_storage_box", StorageService, StorageEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ResourceResponse, "/storage_boxes/{id}", "storage_box", "storage_box", ResponseIdentityClass::ExactResource, NoPagination, ExplicitRetry, NoPermit),
        (GetStorageBoxSnapshot, "get_storage_box_snapshot", StorageService, StorageEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ResourceResponse, "/storage_boxes/{id}/snapshots/{snapshot_id}", "snapshot", "snapshot", ResponseIdentityClass::ExactResource, NoPagination, ExplicitRetry, NoPermit),
        (GetStorageBoxSubaccount, "get_storage_box_subaccount", StorageService, StorageEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ResourceResponse, "/storage_boxes/{id}/subaccounts/{subaccount_id}", "subaccount", "subaccount", ResponseIdentityClass::ExactResource, NoPagination, ExplicitRetry, NoPermit),
        (GetStorageBoxType, "get_storage_box_type", StorageService, StorageEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ResourceResponse, "/storage_box_types/{id}", "storage_box_type", "storage_box_type", ResponseIdentityClass::ExactResource, NoPagination, ExplicitRetry, NoPermit),
        (GetStorageBoxesAction, "get_storage_boxes_action", StorageService, StorageEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ActionResponse, "/storage_boxes/actions/{id}", "-", "action", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetVolume, "get_volume", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ResourceResponse, "/volumes/{id}", "volume", "volume", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetVolumesAction, "get_volumes_action", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ActionResponse, "/volumes/actions/{id}", "-", "action", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetZone, "get_zone", DnsService, CloudEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ResourceResponse, "/zones/{id_or_name}", "zone", "zone", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetZoneRrset, "get_zone_rrset", DnsService, CloudEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ResourceResponse, "/zones/{id_or_name}/rrsets/{rr_name}/{rr_type}", "rrset", "rrset", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetZoneZonefile, "get_zone_zonefile", DnsService, CloudEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ZoneFileResponse, "/zones/{id_or_name}/zonefile", "-", "zonefile", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (GetZonesAction, "get_zones_action", DnsService, CloudEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, ActionResponse, "/zones/actions/{id}", "-", "action", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (ImportZoneZonefile, "import_zone_zonefile", DnsService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/zones/{id_or_name}/actions/import_zonefile", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (ListCertificateActions, "list_certificate_actions", SecurityService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ActionsPageResponse, "/certificates/{id}/actions", "-", "actions,meta", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListCertificates, "list_certificates", SecurityService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ResourcePageResponse, "/certificates", "certificates", "certificates,meta", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListCertificatesActions, "list_certificates_actions", SecurityService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ActionsPageResponse, "/certificates/actions", "-", "actions,meta", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListFirewallActions, "list_firewall_actions", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ActionsPageResponse, "/firewalls/{id}/actions", "-", "actions,meta", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListFirewalls, "list_firewalls", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ResourcePageResponse, "/firewalls", "firewalls", "firewalls,meta", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListFirewallsActions, "list_firewalls_actions", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ActionsPageResponse, "/firewalls/actions", "-", "actions,meta", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListFloatingIpActions, "list_floating_ip_actions", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ActionsPageResponse, "/floating_ips/{id}/actions", "-", "actions,meta", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListFloatingIps, "list_floating_ips", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ResourcePageResponse, "/floating_ips", "floating_ips", "floating_ips,meta", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListFloatingIpsActions, "list_floating_ips_actions", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ActionsPageResponse, "/floating_ips/actions", "-", "actions,meta", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListImageActions, "list_image_actions", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ActionsPageResponse, "/images/{id}/actions", "-", "actions,meta", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListImages, "list_images", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ResourcePageResponse, "/images", "images", "images,meta", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListImagesActions, "list_images_actions", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ActionsPageResponse, "/images/actions", "-", "actions,meta", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListIsos, "list_isos", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ResourcePageResponse, "/isos", "isos", "isos,meta", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListLoadBalancerActions, "list_load_balancer_actions", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ActionsPageResponse, "/load_balancers/{id}/actions", "-", "actions,meta", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListLoadBalancerTypes, "list_load_balancer_types", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ResourcePageResponse, "/load_balancer_types", "load_balancer_types", "load_balancer_types,meta", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListLoadBalancers, "list_load_balancers", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ResourcePageResponse, "/load_balancers", "load_balancers", "load_balancers,meta", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListLoadBalancersActions, "list_load_balancers_actions", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ActionsPageResponse, "/load_balancers/actions", "-", "actions,meta", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListLocations, "list_locations", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ResourcePageResponse, "/locations", "locations", "locations,meta", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListNetworkActions, "list_network_actions", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ActionsPageResponse, "/networks/{id}/actions", "-", "actions,meta", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListNetworks, "list_networks", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ResourcePageResponse, "/networks", "networks", "meta,networks", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListNetworksActions, "list_networks_actions", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ActionsPageResponse, "/networks/actions", "-", "actions,meta", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListPlacementGroups, "list_placement_groups", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ResourcePageResponse, "/placement_groups", "placement_groups", "meta,placement_groups", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListPrimaryIpActions, "list_primary_ip_actions", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ActionsPageResponse, "/primary_ips/{id}/actions", "-", "actions,meta", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListPrimaryIps, "list_primary_ips", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ResourcePageResponse, "/primary_ips", "primary_ips", "meta,primary_ips", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListPrimaryIpsActions, "list_primary_ips_actions", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ActionsPageResponse, "/primary_ips/actions", "-", "actions,meta", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListServerActions, "list_server_actions", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ActionsPageResponse, "/servers/{id}/actions", "-", "actions,meta", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListServerTypes, "list_server_types", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ResourcePageResponse, "/server_types", "server_types", "meta,server_types", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListServers, "list_servers", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ResourcePageResponse, "/servers", "servers", "meta,servers", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListServersActions, "list_servers_actions", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ActionsPageResponse, "/servers/actions", "-", "actions,meta", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListSshKeys, "list_ssh_keys", SecurityService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ResourcePageResponse, "/ssh_keys", "ssh_keys", "meta,ssh_keys", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListStorageBoxActions, "list_storage_box_actions", StorageService, StorageEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ActionsPageResponse, "/storage_boxes/{id}/actions", "-", "actions,meta", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListStorageBoxFolders, "list_storage_box_folders", StorageService, StorageEndpointPolicy, BearerAuthentication, GetMethod, QueryForbidden, BodyForbidden, StatusOk, FoldersResponse, "/storage_boxes/{id}/folders", "-", "folders", ResponseIdentityClass::None, NoPagination, ExplicitRetry, NoPermit),
        (ListStorageBoxSnapshots, "list_storage_box_snapshots", StorageService, StorageEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ResourceListResponse, "/storage_boxes/{id}/snapshots", "snapshots", "snapshots", ResponseIdentityClass::ParentResource, NoPagination, ExplicitRetry, NoPermit),
        (ListStorageBoxSubaccounts, "list_storage_box_subaccounts", StorageService, StorageEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ResourceListResponse, "/storage_boxes/{id}/subaccounts", "subaccounts", "subaccounts", ResponseIdentityClass::ParentResource, NoPagination, ExplicitRetry, NoPermit),
        (ListStorageBoxTypes, "list_storage_box_types", StorageService, StorageEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ResourcePageResponse, "/storage_box_types", "storage_box_types", "meta,storage_box_types", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListStorageBoxes, "list_storage_boxes", StorageService, StorageEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ResourcePageResponse, "/storage_boxes", "storage_boxes", "meta,storage_boxes", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListStorageBoxesActions, "list_storage_boxes_actions", StorageService, StorageEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ActionsPageResponse, "/storage_boxes/actions", "-", "actions,meta", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListVolumeActions, "list_volume_actions", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ActionsPageResponse, "/volumes/{id}/actions", "-", "actions,meta", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListVolumes, "list_volumes", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ResourcePageResponse, "/volumes", "volumes", "meta,volumes", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListVolumesActions, "list_volumes_actions", CloudService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ActionsPageResponse, "/volumes/actions", "-", "actions,meta", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListZoneActions, "list_zone_actions", DnsService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ActionsPageResponse, "/zones/{id_or_name}/actions", "-", "actions,meta", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListZoneRrsets, "list_zone_rrsets", DnsService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ResourcePageResponse, "/zones/{id_or_name}/rrsets", "rrsets", "meta,rrsets", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListZones, "list_zones", DnsService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ResourcePageResponse, "/zones", "zones", "meta,zones", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (ListZonesActions, "list_zones_actions", DnsService, CloudEndpointPolicy, BearerAuthentication, GetMethod, OptionalQuery, BodyForbidden, StatusOk, ActionsPageResponse, "/zones/actions", "-", "actions,meta", ResponseIdentityClass::None, NumberedPagination, ExplicitRetry, NoPermit),
        (PoweroffServer, "poweroff_server", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, BodyForbidden, StatusCreated, ActionResponse, "/servers/{id}/actions/poweroff", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (PoweronServer, "poweron_server", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, BodyForbidden, StatusCreated, ActionResponse, "/servers/{id}/actions/poweron", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (RebootServer, "reboot_server", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, BodyForbidden, StatusCreated, ActionResponse, "/servers/{id}/actions/reboot", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (RebuildServer, "rebuild_server", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, CompositeResponse, "/servers/{id}/actions/rebuild", "-", "-", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (RemoveFirewallFromResources, "remove_firewall_from_resources", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionsResponse, "/firewalls/{id}/actions/remove_from_resources", "-", "actions", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (RemoveLoadBalancerTarget, "remove_load_balancer_target", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/load_balancers/{id}/actions/remove_target", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (RemoveServerFromPlacementGroup, "remove_server_from_placement_group", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, BodyForbidden, StatusCreated, ActionResponse, "/servers/{id}/actions/remove_from_placement_group", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (RemoveZoneRrsetRecords, "remove_zone_rrset_records", DnsService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/zones/{id_or_name}/rrsets/{rr_name}/{rr_type}/actions/remove_records", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (RequestServerConsole, "request_server_console", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, BodyForbidden, StatusCreated, CompositeResponse, "/servers/{id}/actions/request_console", "-", "action,password,wss_url", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (ResetServer, "reset_server", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, BodyForbidden, StatusCreated, ActionResponse, "/servers/{id}/actions/reset", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (ResetServerPassword, "reset_server_password", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, BodyForbidden, StatusCreated, CompositeResponse, "/servers/{id}/actions/reset_password", "-", "-", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (ResetStorageBoxPassword, "reset_storage_box_password", StorageService, StorageEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/storage_boxes/{id}/actions/reset_password", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (ResetStorageBoxSubaccountPassword, "reset_storage_box_subaccount_password", StorageService, StorageEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/storage_boxes/{id}/subaccounts/{subaccount_id}/actions/reset_subaccount_password", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (ResizeVolume, "resize_volume", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/volumes/{id}/actions/resize", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, CostPermit),
        (RetryCertificate, "retry_certificate", SecurityService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, BodyForbidden, StatusCreated, ActionResponse, "/certificates/{id}/actions/retry", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (RollbackStorageBoxSnapshot, "rollback_storage_box_snapshot", StorageService, StorageEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/storage_boxes/{id}/actions/rollback_snapshot", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (SetFirewallRules, "set_firewall_rules", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionsResponse, "/firewalls/{id}/actions/set_rules", "-", "actions", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (SetZoneRrsetRecords, "set_zone_rrset_records", DnsService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/zones/{id_or_name}/rrsets/{rr_name}/{rr_type}/actions/set_records", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (ShutdownServer, "shutdown_server", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, BodyForbidden, StatusCreated, ActionResponse, "/servers/{id}/actions/shutdown", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (UnassignFloatingIp, "unassign_floating_ip", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, BodyForbidden, StatusCreated, ActionResponse, "/floating_ips/{id}/actions/unassign", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (UnassignPrimaryIp, "unassign_primary_ip", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, BodyForbidden, StatusCreated, ActionResponse, "/primary_ips/{id}/actions/unassign", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, DestructivePermit),
        (UpdateCertificate, "update_certificate", SecurityService, CloudEndpointPolicy, BearerAuthentication, PutMethod, QueryForbidden, JsonBody, StatusOk, ResourceResponse, "/certificates/{id}", "certificate", "certificate", ResponseIdentityClass::None, NoPagination, ExplicitRetry, MutationPermit),
        (UpdateFirewall, "update_firewall", CloudService, CloudEndpointPolicy, BearerAuthentication, PutMethod, QueryForbidden, JsonBody, StatusOk, ResourceResponse, "/firewalls/{id}", "firewall", "firewall", ResponseIdentityClass::None, NoPagination, ExplicitRetry, MutationPermit),
        (UpdateFloatingIp, "update_floating_ip", CloudService, CloudEndpointPolicy, BearerAuthentication, PutMethod, QueryForbidden, JsonBody, StatusOk, ResourceResponse, "/floating_ips/{id}", "floating_ip", "floating_ip", ResponseIdentityClass::None, NoPagination, ExplicitRetry, MutationPermit),
        (UpdateImage, "update_image", CloudService, CloudEndpointPolicy, BearerAuthentication, PutMethod, QueryForbidden, JsonBody, StatusOk, ResourceResponse, "/images/{id}", "image", "-", ResponseIdentityClass::None, NoPagination, ExplicitRetry, MutationPermit),
        (UpdateLoadBalancer, "update_load_balancer", CloudService, CloudEndpointPolicy, BearerAuthentication, PutMethod, QueryForbidden, JsonBody, StatusOk, ResourceResponse, "/load_balancers/{id}", "load_balancer", "load_balancer", ResponseIdentityClass::None, NoPagination, ExplicitRetry, MutationPermit),
        (UpdateLoadBalancerService, "update_load_balancer_service", CloudService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/load_balancers/{id}/actions/update_service", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (UpdateNetwork, "update_network", CloudService, CloudEndpointPolicy, BearerAuthentication, PutMethod, QueryForbidden, JsonBody, StatusOk, ResourceResponse, "/networks/{id}", "network", "-", ResponseIdentityClass::None, NoPagination, ExplicitRetry, MutationPermit),
        (UpdatePlacementGroup, "update_placement_group", CloudService, CloudEndpointPolicy, BearerAuthentication, PutMethod, QueryForbidden, JsonBody, StatusOk, ResourceResponse, "/placement_groups/{id}", "placement_group", "placement_group", ResponseIdentityClass::None, NoPagination, ExplicitRetry, MutationPermit),
        (UpdatePrimaryIp, "update_primary_ip", CloudService, CloudEndpointPolicy, BearerAuthentication, PutMethod, QueryForbidden, JsonBody, StatusOk, ResourceResponse, "/primary_ips/{id}", "primary_ip", "primary_ip", ResponseIdentityClass::None, NoPagination, ExplicitRetry, MutationPermit),
        (UpdateServer, "update_server", CloudService, CloudEndpointPolicy, BearerAuthentication, PutMethod, QueryForbidden, JsonBody, StatusOk, ResourceResponse, "/servers/{id}", "server", "-", ResponseIdentityClass::None, NoPagination, ExplicitRetry, MutationPermit),
        (UpdateSshKey, "update_ssh_key", SecurityService, CloudEndpointPolicy, BearerAuthentication, PutMethod, QueryForbidden, JsonBody, StatusOk, ResourceResponse, "/ssh_keys/{id}", "ssh_key", "ssh_key", ResponseIdentityClass::None, NoPagination, ExplicitRetry, MutationPermit),
        (UpdateStorageBox, "update_storage_box", StorageService, StorageEndpointPolicy, BearerAuthentication, PutMethod, QueryForbidden, JsonBody, StatusOk, ResourceResponse, "/storage_boxes/{id}", "storage_box", "storage_box", ResponseIdentityClass::ExactResource, NoPagination, ExplicitRetry, MutationPermit),
        (UpdateStorageBoxAccessSettings, "update_storage_box_access_settings", StorageService, StorageEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/storage_boxes/{id}/actions/update_access_settings", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (UpdateStorageBoxSnapshot, "update_storage_box_snapshot", StorageService, StorageEndpointPolicy, BearerAuthentication, PutMethod, QueryForbidden, JsonBody, StatusOk, ResourceResponse, "/storage_boxes/{id}/snapshots/{snapshot_id}", "snapshot", "snapshot", ResponseIdentityClass::ExactResource, NoPagination, ExplicitRetry, MutationPermit),
        (UpdateStorageBoxSubaccount, "update_storage_box_subaccount", StorageService, StorageEndpointPolicy, BearerAuthentication, PutMethod, QueryForbidden, JsonBody, StatusOk, ResourceResponse, "/storage_boxes/{id}/subaccounts/{subaccount_id}", "subaccount", "subaccount", ResponseIdentityClass::ExactResource, NoPagination, ExplicitRetry, MutationPermit),
        (UpdateStorageBoxSubaccountAccessSettings, "update_storage_box_subaccount_access_settings", StorageService, StorageEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusCreated, ActionResponse, "/storage_boxes/{id}/subaccounts/{subaccount_id}/actions/update_access_settings", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
        (UpdateVolume, "update_volume", CloudService, CloudEndpointPolicy, BearerAuthentication, PutMethod, QueryForbidden, JsonBody, StatusOk, ResourceResponse, "/volumes/{id}", "volume", "volume", ResponseIdentityClass::None, NoPagination, ExplicitRetry, MutationPermit),
        (UpdateZone, "update_zone", DnsService, CloudEndpointPolicy, BearerAuthentication, PutMethod, QueryForbidden, JsonBody, StatusOk, ResourceResponse, "/zones/{id_or_name}", "zone", "zone", ResponseIdentityClass::None, NoPagination, ExplicitRetry, MutationPermit),
        (UpdateZoneRrset, "update_zone_rrset", DnsService, CloudEndpointPolicy, BearerAuthentication, PutMethod, QueryForbidden, JsonBody, StatusOk, ResourceResponse, "/zones/{id_or_name}/rrsets/{rr_name}/{rr_type}", "rrset", "rrset", ResponseIdentityClass::None, NoPagination, ExplicitRetry, MutationPermit),
        (UpdateZoneRrsetRecords, "update_zone_rrset_records", DnsService, CloudEndpointPolicy, BearerAuthentication, PostMethod, QueryForbidden, JsonBody, StatusOk, ActionResponse, "/zones/{id_or_name}/rrsets/{rr_name}/{rr_type}/actions/update_records", "-", "action", ResponseIdentityClass::None, NoPagination, NeverRetry, MutationPermit),
);
