// Generated by scripts/generate_cratesio_personal.py; source review required.
use crate::catalog::schema::Node;
pub(super) const CONFIRM_USER_EMAIL: usize = 2;
pub(super) const FOLLOW_CRATE: usize = 5;
pub(super) const UNFOLLOW_CRATE: usize = 8;
pub(super) const ACCEPT_CRATE_OWNER_INVITATION_WITH_TOKEN: usize = 14;
pub(super) const HANDLE_CRATE_OWNER_INVITATION: usize = 20;
#[cfg(test)]
pub(super) const HANDLE_CRATE_OWNER_INVITATION_BODY: usize = 26;
pub(super) const UPDATE_EMAIL_NOTIFICATIONS: usize = 29;
pub(super) const RESEND_EMAIL_VERIFICATION: usize = 32;
pub(super) const UPDATE_USER: usize = 35;
#[cfg(test)]
pub(super) const UPDATE_USER_BODY: usize = 43;
#[rustfmt::skip]
pub(super) const NODES: &[Node] = &[
    Node::Bool,
    Node::Any,
    Node::Object(&[("ok", 0, true)], Some(1)),
    Node::Bool,
    Node::Any,
    Node::Object(&[("ok", 3, true)], Some(4)),
    Node::Bool,
    Node::Any,
    Node::Object(&[("ok", 6, true)], Some(7)),
    Node::Bool,
    Node::Integer(2147483647),
    Node::Any,
    Node::Object(&[("accepted", 9, true),("crate_id", 10, true)], Some(11)),
    Node::Any,
    Node::Object(&[("crate_owner_invitation", 12, true)], Some(13)),
    Node::Bool,
    Node::Integer(2147483647),
    Node::Any,
    Node::Object(&[("accepted", 15, true),("crate_id", 16, true)], Some(17)),
    Node::Any,
    Node::Object(&[("crate_owner_invitation", 18, true)], Some(19)),
    Node::Bool,
    Node::Integer(2147483647),
    Node::Any,
    Node::Object(&[("accepted", 21, true),("crate_id", 22, true)], Some(23)),
    Node::Any,
    Node::Object(&[("crate_owner_invite", 24, true)], Some(25)),
    Node::Bool,
    Node::Any,
    Node::Object(&[("ok", 27, true)], Some(28)),
    Node::Bool,
    Node::Any,
    Node::Object(&[("ok", 30, true)], Some(31)),
    Node::Bool,
    Node::Any,
    Node::Object(&[("ok", 33, true)], Some(34)),
    Node::Text,
    Node::Nullable(36),
    Node::Bool,
    Node::Nullable(38),
    Node::Any,
    Node::Object(&[("email", 37, false),("publish_notifications", 39, false)], Some(40)),
    Node::Any,
    Node::Object(&[("user", 41, true)], Some(42)),
];
