use super::{RobotClientMutationOperation, RobotClientOperation, RobotDirectClientOperation};
use crate::robot::*;

fn operation<T: RobotClientOperation>() {}
fn direct<T: RobotDirectClientOperation>() {}
fn mutation<T: RobotClientMutationOperation>() {}

macro_rules! assert_operations {
    ($($type:ty),+ $(,)?) => {$ (operation::<$type>();)+ };
}

#[test]
fn every_active_robot_request_has_a_typed_client_contract() {
    assert_operations!(
        RobotServerListRequest,
        RobotServerGetRequest,
        RobotServerUpdateRequest<'static>,
        RobotServerCancellationGetRequest,
        RobotServerCancellationCreateRequest<'static>,
        RobotServerCancellationDeleteRequest,
        RobotIpCancellationGetRequest,
        RobotIpCancellationCreateRequest,
        RobotIpCancellationDeleteRequest,
        RobotSubnetCancellationGetRequest,
        RobotSubnetCancellationCreateRequest,
        RobotSubnetCancellationDeleteRequest,
        RobotIpListRequest,
        RobotIpGetRequest,
        RobotIpUpdateRequest,
        RobotIpMacGetRequest,
        RobotIpMacSetRequest,
        RobotIpMacDeleteRequest,
        RobotSubnetListRequest,
        RobotSubnetGetRequest,
        RobotSubnetUpdateRequest,
        RobotSubnetMacGetRequest,
        RobotSubnetMacSetRequest,
        RobotSubnetMacDeleteRequest,
        RobotResetListRequest,
        RobotResetGetRequest,
        RobotResetExecuteRequest<'static>,
        RobotFailoverListRequest,
        RobotFailoverGetRequest,
        RobotFailoverRerouteRequest,
        RobotFailoverDeleteRouteRequest,
        RobotWolGetRequest,
        RobotWolSendRequest<'static>,
        RobotBootGetRequest,
        RobotRescueGetRequest,
        RobotRescueActivateRequest<'static>,
        RobotRescueDeactivateRequest,
        RobotRescueLastRequest,
        RobotLinuxGetRequest,
        RobotLinuxActivateRequest<'static>,
        RobotLinuxDeactivateRequest,
        RobotLinuxLastRequest,
        RobotVncGetRequest,
        RobotVncActivateRequest<'static>,
        RobotVncDeactivateRequest,
        RobotWindowsGetRequest,
        RobotWindowsActivateRequest<'static>,
        RobotWindowsDeactivateRequest,
        RobotRdnsListRequest,
        RobotRdnsGetRequest,
        RobotRdnsSetRequest,
        RobotRdnsUpdateRequest,
        RobotRdnsDeleteRequest,
        RobotTrafficRequest,
        RobotSshKeyListRequest,
        RobotSshKeyCreateRequest<'static>,
        RobotSshKeyGetRequest,
        RobotSshKeyUpdateRequest,
        RobotSshKeyDeleteRequest,
        RobotStandardProductListRequest,
        RobotStandardProductGetRequest,
        RobotStandardTransactionListRequest,
        RobotStandardOrderCreateRequest<'static>,
        RobotStandardTransactionGetRequest,
        RobotMarketProductListRequest,
        RobotMarketProductGetRequest,
        RobotMarketTransactionListRequest,
        RobotMarketOrderCreateRequest<'static>,
        RobotMarketTransactionGetRequest,
        RobotAddonProductListRequest,
        RobotAddonTransactionListRequest,
        RobotAddonOrderCreateRequest<'static, 'static>,
        RobotAddonTransactionGetRequest,
        RobotOrderCurrencyRequest,
        RobotFirewallGetRequest,
        RobotFirewallReplaceRequest<'static>,
        RobotFirewallDeleteRequest,
        RobotFirewallTemplateListRequest,
        RobotFirewallTemplateCreateRequest<'static>,
        RobotFirewallTemplateGetRequest,
        RobotFirewallTemplateUpdateRequest<'static>,
        RobotFirewallTemplateDeleteRequest,
        RobotVSwitchListRequest,
        RobotVSwitchCreateRequest,
        RobotVSwitchGetRequest,
        RobotVSwitchUpdateRequest,
        RobotVSwitchCancelRequest,
        RobotVSwitchAddServersRequest<'static>,
        RobotVSwitchRemoveServersRequest<'static>,
    );
}

#[test]
fn read_only_and_generic_mutation_routes_remain_sealed_and_complete() {
    macro_rules! assert_direct {
        ($($type:ty),+ $(,)?) => {$ (direct::<$type>();)+ };
    }
    assert_direct!(
        RobotServerListRequest,
        RobotServerGetRequest,
        RobotServerCancellationGetRequest,
        RobotIpCancellationGetRequest,
        RobotSubnetCancellationGetRequest,
        RobotIpListRequest,
        RobotIpGetRequest,
        RobotIpMacGetRequest,
        RobotSubnetListRequest,
        RobotSubnetGetRequest,
        RobotSubnetMacGetRequest,
        RobotResetListRequest,
        RobotResetGetRequest,
        RobotFailoverListRequest,
        RobotFailoverGetRequest,
        RobotWolGetRequest,
        RobotBootGetRequest,
        RobotRescueGetRequest,
        RobotRescueLastRequest,
        RobotLinuxGetRequest,
        RobotLinuxLastRequest,
        RobotVncGetRequest,
        RobotWindowsGetRequest,
        RobotRdnsListRequest,
        RobotRdnsGetRequest,
        RobotTrafficRequest,
        RobotSshKeyListRequest,
        RobotSshKeyGetRequest,
        RobotFirewallGetRequest,
        RobotFirewallTemplateListRequest,
        RobotFirewallTemplateGetRequest,
        RobotVSwitchListRequest,
        RobotVSwitchGetRequest,
        RobotStandardProductListRequest,
        RobotStandardProductGetRequest,
        RobotMarketProductListRequest,
        RobotMarketProductGetRequest,
        RobotAddonProductListRequest,
        RobotOrderCurrencyRequest,
        RobotStandardTransactionListRequest,
        RobotStandardTransactionGetRequest,
        RobotMarketTransactionListRequest,
        RobotMarketTransactionGetRequest,
        RobotAddonTransactionListRequest,
        RobotAddonTransactionGetRequest,
    );

    macro_rules! assert_mutation {
        ($($type:ty),+ $(,)?) => {$ (mutation::<$type>();)+ };
    }
    assert_mutation!(
        RobotServerUpdateRequest<'static>,
        RobotRescueActivateRequest<'static>,
        RobotRescueDeactivateRequest,
        RobotLinuxActivateRequest<'static>,
        RobotLinuxDeactivateRequest,
        RobotVncActivateRequest<'static>,
        RobotVncDeactivateRequest,
        RobotWindowsActivateRequest<'static>,
        RobotWindowsDeactivateRequest,
    );
}
