// Generated by scripts/generate_request_contract_inventory.py.
impl SourceQueryOperation {
    /// Source-locked `get_actions` query operation.
    pub const GET_ACTIONS: Self = Self("get_actions");
    /// Source-locked `get_load_balancer_metrics` query operation.
    pub const GET_LOAD_BALANCER_METRICS: Self = Self("get_load_balancer_metrics");
    /// Source-locked `get_server_metrics` query operation.
    pub const GET_SERVER_METRICS: Self = Self("get_server_metrics");
    /// Source-locked `list_certificate_actions` query operation.
    pub const LIST_CERTIFICATE_ACTIONS: Self = Self("list_certificate_actions");
    /// Source-locked `list_certificates` query operation.
    pub const LIST_CERTIFICATES: Self = Self("list_certificates");
    /// Source-locked `list_certificates_actions` query operation.
    pub const LIST_CERTIFICATES_ACTIONS: Self = Self("list_certificates_actions");
    /// Source-locked `list_firewall_actions` query operation.
    pub const LIST_FIREWALL_ACTIONS: Self = Self("list_firewall_actions");
    /// Source-locked `list_firewalls` query operation.
    pub const LIST_FIREWALLS: Self = Self("list_firewalls");
    /// Source-locked `list_firewalls_actions` query operation.
    pub const LIST_FIREWALLS_ACTIONS: Self = Self("list_firewalls_actions");
    /// Source-locked `list_floating_ip_actions` query operation.
    pub const LIST_FLOATING_IP_ACTIONS: Self = Self("list_floating_ip_actions");
    /// Source-locked `list_floating_ips` query operation.
    pub const LIST_FLOATING_IPS: Self = Self("list_floating_ips");
    /// Source-locked `list_floating_ips_actions` query operation.
    pub const LIST_FLOATING_IPS_ACTIONS: Self = Self("list_floating_ips_actions");
    /// Source-locked `list_image_actions` query operation.
    pub const LIST_IMAGE_ACTIONS: Self = Self("list_image_actions");
    /// Source-locked `list_images` query operation.
    pub const LIST_IMAGES: Self = Self("list_images");
    /// Source-locked `list_images_actions` query operation.
    pub const LIST_IMAGES_ACTIONS: Self = Self("list_images_actions");
    /// Source-locked `list_isos` query operation.
    pub const LIST_ISOS: Self = Self("list_isos");
    /// Source-locked `list_load_balancer_actions` query operation.
    pub const LIST_LOAD_BALANCER_ACTIONS: Self = Self("list_load_balancer_actions");
    /// Source-locked `list_load_balancer_types` query operation.
    pub const LIST_LOAD_BALANCER_TYPES: Self = Self("list_load_balancer_types");
    /// Source-locked `list_load_balancers` query operation.
    pub const LIST_LOAD_BALANCERS: Self = Self("list_load_balancers");
    /// Source-locked `list_load_balancers_actions` query operation.
    pub const LIST_LOAD_BALANCERS_ACTIONS: Self = Self("list_load_balancers_actions");
    /// Source-locked `list_locations` query operation.
    pub const LIST_LOCATIONS: Self = Self("list_locations");
    /// Source-locked `list_network_actions` query operation.
    pub const LIST_NETWORK_ACTIONS: Self = Self("list_network_actions");
    /// Source-locked `list_networks` query operation.
    pub const LIST_NETWORKS: Self = Self("list_networks");
    /// Source-locked `list_networks_actions` query operation.
    pub const LIST_NETWORKS_ACTIONS: Self = Self("list_networks_actions");
    /// Source-locked `list_placement_groups` query operation.
    pub const LIST_PLACEMENT_GROUPS: Self = Self("list_placement_groups");
    /// Source-locked `list_primary_ip_actions` query operation.
    pub const LIST_PRIMARY_IP_ACTIONS: Self = Self("list_primary_ip_actions");
    /// Source-locked `list_primary_ips` query operation.
    pub const LIST_PRIMARY_IPS: Self = Self("list_primary_ips");
    /// Source-locked `list_primary_ips_actions` query operation.
    pub const LIST_PRIMARY_IPS_ACTIONS: Self = Self("list_primary_ips_actions");
    /// Source-locked `list_server_actions` query operation.
    pub const LIST_SERVER_ACTIONS: Self = Self("list_server_actions");
    /// Source-locked `list_server_types` query operation.
    pub const LIST_SERVER_TYPES: Self = Self("list_server_types");
    /// Source-locked `list_servers` query operation.
    pub const LIST_SERVERS: Self = Self("list_servers");
    /// Source-locked `list_servers_actions` query operation.
    pub const LIST_SERVERS_ACTIONS: Self = Self("list_servers_actions");
    /// Source-locked `list_ssh_keys` query operation.
    pub const LIST_SSH_KEYS: Self = Self("list_ssh_keys");
    /// Source-locked `list_storage_box_actions` query operation.
    pub const LIST_STORAGE_BOX_ACTIONS: Self = Self("list_storage_box_actions");
    /// Source-locked `list_storage_box_folders` query operation.
    pub const LIST_STORAGE_BOX_FOLDERS: Self = Self("list_storage_box_folders");
    /// Source-locked `list_storage_box_snapshots` query operation.
    pub const LIST_STORAGE_BOX_SNAPSHOTS: Self = Self("list_storage_box_snapshots");
    /// Source-locked `list_storage_box_subaccounts` query operation.
    pub const LIST_STORAGE_BOX_SUBACCOUNTS: Self = Self("list_storage_box_subaccounts");
    /// Source-locked `list_storage_box_types` query operation.
    pub const LIST_STORAGE_BOX_TYPES: Self = Self("list_storage_box_types");
    /// Source-locked `list_storage_boxes` query operation.
    pub const LIST_STORAGE_BOXES: Self = Self("list_storage_boxes");
    /// Source-locked `list_storage_boxes_actions` query operation.
    pub const LIST_STORAGE_BOXES_ACTIONS: Self = Self("list_storage_boxes_actions");
    /// Source-locked `list_volume_actions` query operation.
    pub const LIST_VOLUME_ACTIONS: Self = Self("list_volume_actions");
    /// Source-locked `list_volumes` query operation.
    pub const LIST_VOLUMES: Self = Self("list_volumes");
    /// Source-locked `list_volumes_actions` query operation.
    pub const LIST_VOLUMES_ACTIONS: Self = Self("list_volumes_actions");
    /// Source-locked `list_zone_actions` query operation.
    pub const LIST_ZONE_ACTIONS: Self = Self("list_zone_actions");
    /// Source-locked `list_zone_rrsets` query operation.
    pub const LIST_ZONE_RRSETS: Self = Self("list_zone_rrsets");
    /// Source-locked `list_zones` query operation.
    pub const LIST_ZONES: Self = Self("list_zones");
    /// Source-locked `list_zones_actions` query operation.
    pub const LIST_ZONES_ACTIONS: Self = Self("list_zones_actions");
}
