#!/usr/bin/env python3
"""Bind successful three-mode client fixtures to the reviewed API inventory."""
import argparse
import csv
import io
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCOPE = ROOT / "docs/CRATESIO_API_SCOPE.tsv"
TABLE = ROOT / "crates/cloud-sdk-cratesio/src/client/asynchronous/tests/coverage_routes.rs"
MODES = frozenset(("blocking", "local", "send"))
MARKER = "CLOUD_SDK_EXECUTION:"


def rows(text):
    result = []
    identities = set()
    routes = set()
    for row in csv.DictReader(io.StringIO(text), delimiter="\t"):
        if row["classification"] != "included":
            continue
        identity, method, path = (row[key] for key in ("operation_id", "method", "path"))
        if (not re.fullmatch(r"[a-z][a-z0-9_]*", identity)
                or method not in {"GET", "POST", "PUT", "PATCH", "DELETE"}
                or not re.fullmatch(r"/api/v1/[a-z0-9_/{}/]+", path)):
            raise ValueError("invalid operation identity or route")
        if identity in identities or (method, path) in routes:
            raise ValueError("duplicate operation identity or route")
        identities.add(identity)
        routes.add((method, path))
        result.append((identity, method, path))
    if not result:
        raise ValueError("empty admitted operation inventory")
    return sorted(result)


def render(inventory):
    lines = ["// Generated by scripts/check_cratesio_execution_coverage.py --write-routes.",
             "#[rustfmt::skip]",
             "pub(super) const ROUTES: &[(&str, &str, &str)] = &["]
    for identity, method, path in inventory:
        lines.extend(["    (", f'        "{identity}",', f'        "{method}",',
                      f'        "{path}",', "    ),"])
    return "\n".join(lines + ["];", ""])


def coverage(inventory, output):
    observed = {identity: set() for identity, _, _ in inventory}
    for line in output.splitlines():
        if MARKER not in line:
            continue
        payload = line.split(MARKER, 1)[1]
        fields = payload.split(":")
        if len(fields) != 2 or fields[0] not in observed or fields[1] not in MODES:
            raise ValueError("unrecognized execution witness")
        observed[fields[0]].add(fields[1])
    return {identity: sorted(MODES - modes) for identity, modes in observed.items() if modes != MODES}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    modes = parser.add_mutually_exclusive_group()
    modes.add_argument("--write-routes", action="store_true")
    modes.add_argument("--check-routes", action="store_true")
    modes.add_argument("--report", action="store_true", help="report progress, not a completion gate")
    args = parser.parse_args()
    inventory = rows(SCOPE.read_text(encoding="ascii"))
    expected = render(inventory)
    if args.write_routes:
        TABLE.write_text(expected, encoding="ascii")
        return 0
    if TABLE.read_text(encoding="ascii") != expected:
        raise ValueError("execution routes are stale; regenerate and review")
    if args.check_routes:
        print(f"{len(inventory)} execution routes match the admitted inventory.")
        return 0
    command = ["cargo", "test", "--locked", "-p", "cloud-sdk-cratesio", "--all-features",
               "--lib", "--", "--nocapture", "--test-threads=1"]
    result = subprocess.run(command, cwd=ROOT, capture_output=True, text=True, check=False)
    if result.returncode:
        raise ValueError("provider fixture suite failed; no execution evidence accepted")
    missing = coverage(inventory, result.stdout)
    print(f"Three-mode execution evidence: {len(inventory) - len(missing)}/{len(inventory)} operations.")
    for identity, modes in missing.items():
        print(f"Missing: {identity}: {', '.join(modes)}")
    if missing:
        print("Commit 20 execution gate remains OPEN.")
    return int(bool(missing) and not args.report)


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError, KeyError) as error:
        raise SystemExit(f"crates.io execution coverage: {error}") from None
