"""Fixtures for prepared-operation coverage gate regressions."""

from __future__ import annotations

import subprocess
from pathlib import Path

from check_prepared_operation_coverage import cargo_library_source

ROOT = Path(__file__).resolve().parents[1]
CHECKER = ROOT / "scripts" / "check_prepared_operation_coverage.py"
LOCKS = ROOT / "tools" / "prepared-coverage-check" / "locks"
ENDPOINT_DEFINITIONS = (LOCKS / "endpoints.rs").read_text(encoding="utf-8")
BODY_DEFINITIONS = (LOCKS / "bodies.rs").read_text(encoding="utf-8")
HEADER = """# Matrix

## Operations

| API | Group | Method | Path | Operation | Owner | Pagination | Sorting | Action | Deprecated | Status |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
"""
ENDPOINTS = """endpoint_wire!(
    TestEndpoint,
    endpoint => (),
    (),
    match endpoint {
        TestEndpoint::Read => "read_test",
        TestEndpoint::Write => "write_test",
    },
    false,
    ()
);"""
BODIES = 'body_wire!(WriteRequest, request => (), "write_test", write_test);'
MANIFEST = """[package]
name = "prepared-coverage-fixture"
version = "0.0.0"
edition = "2024"
"""
LOCKFILE = """# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "prepared-coverage-fixture"
version = "0.0.0"
"""


def row(operation: str, *, deprecated: str = "no") -> str:
    """Build one API-matrix fixture row."""
    status = "deferred-deprecated" if deprecated == "yes" else "implemented"
    return (
        f"| cloud | Test | POST | `/test` | `{operation}` | `test` | no | no | "
        f"none | {deprecated} | {status} |\n"
    )


def assert_ambiguous_metadata_rejected(directory: Path) -> None:
    """Require fail-closed parsing for missing or ambiguous Cargo evidence."""
    manifest_path = (directory / "Cargo.toml").resolve(strict=True)
    source_path = (directory / "src" / "lib.rs").resolve(strict=True)
    package = {
        "manifest_path": str(manifest_path),
        "targets": [{"kind": ["lib"], "src_path": str(source_path)}],
    }
    for packages in ([], [package, package]):
        try:
            cargo_library_source({"packages": packages}, manifest_path)
        except ValueError as error:
            assert "package is missing or ambiguous" in str(error), error
        else:
            raise AssertionError("ambiguous package metadata was accepted")
    ambiguous_targets = dict(package)
    ambiguous_targets["targets"] = package["targets"] * 2
    try:
        cargo_library_source({"packages": [ambiguous_targets]}, manifest_path)
    except ValueError as error:
        assert "library target is missing or ambiguous" in str(error), error
    else:
        raise AssertionError("ambiguous library metadata was accepted")


def assert_accepts_operation_mutations_rejected(directory: Path) -> None:
    """Reject compatibility methods detached from their canonical parameter."""
    for scrutinee in ('"write_test"', "self.operation_key()", "OTHER_VALUE"):
        result = run(
            directory,
            bodies=(
                "impl crate::prepared::BodyWire for Fake { "
                "fn operation_key(self) -> &'static str { \"write_test\" } "
                "fn accepts_operation(self, operation_key: &str) -> bool { "
                f'matches!({scrutinee}, "write_test") }} }}'
            ),
        )
        assert result.returncode == 1, result
        assert "must match the operation_key parameter" in result.stderr
    invalid_signature = run(
        directory,
        bodies=(
            "impl crate::prepared::BodyWire for Fake { "
            "fn operation_key(self) -> &'static str { \"write_test\" } "
            "fn accepts_operation(self) -> bool { "
            'matches!(operation_key, "write_test") } }'
        ),
    )
    assert invalid_signature.returncode == 1, invalid_signature
    assert "must use the canonical signature" in invalid_signature.stderr
    query_scrutinee = run(
        directory,
        endpoints=(
            ENDPOINTS
            + "\nimpl crate::prepared::QueryWire for Fake { "
            + "fn operation_key(self) -> &'static str { \"read_test\" } "
            + "fn accepts_operation(self, operation_key: &str) -> bool { "
            + 'matches!(OTHER_VALUE, "read_test") } }'
        ),
    )
    assert query_scrutinee.returncode == 1, query_scrutinee
    assert "must match the operation_key parameter" in query_scrutinee.stderr
    noncanonical_query = run(
        directory,
        endpoints=ENDPOINTS + "\nimpl QueryWire for Fake {}\n",
    )
    assert noncanonical_query.returncode == 1, noncanonical_query
    assert "must use crate::prepared::QueryWire" in noncanonical_query.stderr
    parent_macro = (
        "macro_rules! permissive { () => { "
        "fn accepts_operation(self, _operation_key: &str) -> bool { true } "
        "}; }\npub mod prepared;\n"
    )
    body_macro = run(
        directory,
        crate_root=parent_macro,
        bodies=(
            "impl crate::prepared::BodyWire for Fake { "
            "fn operation_key(self) -> &'static str { \"write_test\" } "
            "permissive!(); }"
        ),
    )
    assert_impl_macro_rejected(body_macro)
    query_macro = run(
        directory,
        crate_root=parent_macro,
        endpoints=(
            ENDPOINTS
            + "\nimpl crate::prepared::QueryWire for Fake { permissive!(); }\n"
        ),
    )
    assert_impl_macro_rejected(query_macro)
    endpoint_macro = run(
        directory,
        crate_root=parent_macro,
        endpoints=(
            "endpoint_wire!(Real, value => (), (), match value { "
            'Real::Write => "write_test" }, false, ());\n'
            "impl crate::prepared::EndpointWire for Fake { permissive!(); }\n"
        ),
    )
    assert_impl_macro_rejected(endpoint_macro)
    body_include = run(
        directory,
        bodies=(
            "impl crate::prepared::BodyWire for Fake { "
            "fn operation_key(self) -> &'static str { \"write_test\" } "
            'include!("permissive.inc"); }'
        ),
    )
    assert_impl_macro_rejected(body_include)
    query_include = run(
        directory,
        endpoints=(
            ENDPOINTS
            + '\nimpl crate::prepared::QueryWire for Fake { include!("permissive.inc"); }\n'
        ),
    )
    assert_impl_macro_rejected(query_include)
    assert_attributed_impl_items_rejected(directory)
    assert_hidden_module_evidence_rejected(directory)


def assert_impl_macro_rejected(result: subprocess.CompletedProcess[str]) -> None:
    """Require reserved wire implementation macros to fail closed."""
    assert result.returncode == 1, result
    assert "macros inside prepared wire implementations" in result.stderr


def assert_attributed_impl_items_rejected(directory: Path) -> None:
    """Reject procedural attributes on every reserved associated item form."""
    body_function = run(
        directory,
        bodies=(
            "impl crate::prepared::BodyWire for Fake { "
            "fn operation_key(self) -> &'static str { \"write_test\" } "
            "#[generate_accepts] fn placeholder() {} }"
        ),
    )
    assert_impl_attribute_rejected(body_function)
    query_function = run(
        directory,
        endpoints=(
            ENDPOINTS
            + "\nimpl crate::prepared::QueryWire for Fake { "
            + "#[generate_accepts] fn placeholder() {} }\n"
        ),
    )
    assert_impl_attribute_rejected(query_function)
    endpoint_function = run(
        directory,
        endpoints=(
            "endpoint_wire!(Real, value => (), (), match value { "
            'Real::Write => "write_test" }, false, ());\n'
            "impl crate::prepared::EndpointWire for Fake { "
            "#[generate_key] fn placeholder() {} }\n"
        ),
    )
    assert_impl_attribute_rejected(endpoint_function)
    body_constant = run(
        directory,
        bodies=(
            "impl crate::prepared::BodyWire for Fake { "
            "fn operation_key(self) -> &'static str { \"write_test\" } "
            "#[generate_accepts] const PLACEHOLDER: () = (); }"
        ),
    )
    assert_impl_attribute_rejected(body_constant)
    query_type = run(
        directory,
        endpoints=(
            ENDPOINTS
            + "\nimpl crate::prepared::QueryWire for Fake { "
            + "#[generate_accepts] type Placeholder = (); }\n"
        ),
    )
    assert_impl_attribute_rejected(query_type)


def assert_impl_attribute_rejected(result: subprocess.CompletedProcess[str]) -> None:
    """Require associated-item procedural attributes to fail closed."""
    assert result.returncode == 1, result
    assert "attributes inside prepared wire implementations" in result.stderr


def assert_hidden_module_evidence_rejected(directory: Path) -> None:
    """Reject attributed, nested, discarded, and opaque implementation evidence."""
    custom_attribute = run(
        directory,
        bodies=BODIES + "\n#[generate_impl]\nstruct Marker;\n",
    )
    assert_module_attribute_rejected(custom_attribute)
    derive_attribute = run(
        directory,
        bodies=BODIES + "\n#[derive(GenerateImpl)]\nstruct Marker;\n",
    )
    assert_module_attribute_rejected(derive_attribute)
    hidden_impl = (
        "impl crate::prepared::BodyWire for Hidden { "
        "fn operation_key(self) -> &'static str { \"write_test\" } "
        "fn accepts_operation(self, _operation_key: &str) -> bool { true } }"
    )
    nested_function = run(
        directory,
        bodies=BODIES + f"\nfn helper() {{ {hidden_impl} }}\n",
    )
    assert_nested_item_rejected(nested_function)
    nested_constant = run(
        directory,
        bodies=BODIES + f"\nconst HIDDEN: () = {{ {hidden_impl} () }};\n",
    )
    assert_nested_item_rejected(nested_constant)
    nested_wire_method = run(
        directory,
        bodies=(
            "impl crate::prepared::BodyWire for Fake { "
            "fn operation_key(self) -> &'static str { "
            "impl crate::prepared::QueryWire for Hidden { "
            "fn operation_key(self) -> &'static str { \"read_test\" } } "
            '"write_test" } }'
        ),
    )
    assert_nested_item_rejected(nested_wire_method)
    nested_macro = run(
        directory,
        bodies=BODIES + "\nfn helper() { permissive!(); }\n",
    )
    assert_nested_item_rejected(nested_macro)
    endpoint_argument = run(
        directory,
        endpoints=(
            "endpoint_wire!(TestEndpoint, endpoint => { "
            f"{hidden_impl} () }}, (), match endpoint {{ "
            'TestEndpoint::Read => "read_test", '
            'TestEndpoint::Write => "write_test" }, false, ());'
        ),
    )
    assert_nested_item_rejected(endpoint_argument)
    body_argument = run(
        directory,
        bodies=(
            "body_wire!(WriteRequest, request => { "
            f'{hidden_impl} () }}, "write_test", write_test);'
        ),
    )
    assert_nested_item_rejected(body_argument)
    query_argument = run(
        directory,
        endpoints=(
            ENDPOINTS
            + "\nquery_wire!(Fake, request => { "
            + f"{hidden_impl} () }});\n"
        ),
    )
    assert_nested_item_rejected(query_argument)
    hidden_type = f"[u8; {{ {hidden_impl} 1 }}]"
    hidden_writer = f"Writer::<{{ {hidden_impl} 1 }}>::write"
    hidden_adapter_fields = [
        run(
            directory,
            endpoints=(
                f"endpoint_wire!({hidden_type}, endpoint => (), (), match endpoint {{ "
                'TestEndpoint::Read => "read_test", TestEndpoint::Write => "write_test" '
                "}, false, ());"
            ),
        ),
        run(directory, bodies=f'body_wire!({hidden_type}, request => (), "write_test", write);'),
        run(
            directory,
            endpoints=ENDPOINTS + f"\nquery_wire!({hidden_type}, request => ());\n",
        ),
        run(directory, bodies=f'body_component!({hidden_type}, "write_test", write);'),
        run(
            directory,
            bodies=f'body_wire!(WriteRequest, request => (), "write_test", {hidden_writer});',
        ),
        run(
            directory,
            bodies=f'body_component!(WriteRequest, "write_test", {hidden_writer});',
        ),
        run(
            directory,
            endpoint_definitions=(
                ENDPOINT_DEFINITIONS + f"\nimpl_endpoint_prepare!({hidden_type});\n"
            ),
        ),
    ]
    for result in hidden_adapter_fields:
        assert_nested_item_rejected(result)
    opaque_macro_fields = [
        run(
            directory,
            endpoints=(
                "endpoint_wire!(TestEndpoint, endpoint => (), (), match endpoint { "
                'TestEndpoint::Read => "read_test", TestEndpoint::Write => "write_test" }, '
                f"matches!({{ {hidden_impl} endpoint }}, TestEndpoint::Read), ());"
            ),
        ),
        run(
            directory,
            endpoints=ENDPOINTS + "\nquery_wire!(Fake, request => opaque!());\n",
        ),
        run(directory, bodies='body_wire!(opaque!(), request => (), "write_test", write);'),
        run(
            directory,
            endpoints=(
                "endpoint_wire!(TestEndpoint, endpoint => (), (), match endpoint { "
                'opaque!() => "read_test", TestEndpoint::Write => "write_test" '
                "}, false, ());"
            ),
        ),
    ]
    for result in opaque_macro_fields:
        assert_nested_item_rejected(result)


def assert_module_attribute_rejected(result: subprocess.CompletedProcess[str]) -> None:
    """Require all module-scope evidence items to be unattributed."""
    assert result.returncode == 1, result
    assert "attributes on prepared-operation evidence" in result.stderr


def assert_nested_item_rejected(result: subprocess.CompletedProcess[str]) -> None:
    """Require hidden nested items and opaque macros to fail closed."""
    assert result.returncode == 1, result
    assert "nested items or opaque macros" in result.stderr


def run(
    directory: Path,
    *,
    endpoints: str = ENDPOINTS,
    bodies: str = BODIES,
    endpoint_definitions: str = ENDPOINT_DEFINITIONS,
    body_definitions: str = BODY_DEFINITIONS,
    manifest: str = MANIFEST,
    crate_root: str = "pub mod prepared;\n",
    prepared_root: str = "mod endpoints;\nmod bodies;\n",
    endpoint_modules: str = "mod test;\n",
    body_modules: str = "mod test;\n",
    extra_endpoint_files: dict[str, str] | None = None,
    extra_source_files: dict[str, str] | None = None,
    write_endpoint_module: bool = True,
) -> subprocess.CompletedProcess[str]:
    """Run the coverage gate against one isolated canonical module graph."""
    matrix = directory / "matrix.md"
    matrix.write_text(HEADER + row("read_test") + row("write_test"), encoding="utf-8")
    body_lock = directory / "bodies.txt"
    body_lock.write_text("write_test\n", encoding="ascii")
    source_dir = directory / "src"
    source_dir.mkdir(parents=True, exist_ok=True)
    for source_file in source_dir.glob("*.rs"):
        source_file.unlink()
    (directory / "Cargo.toml").write_text(manifest, encoding="utf-8")
    (directory / "Cargo.lock").write_text(LOCKFILE, encoding="utf-8")
    prepared_dir = source_dir / "prepared"
    endpoint_dir = prepared_dir / "endpoints"
    body_dir = prepared_dir / "bodies"
    endpoint_dir.mkdir(parents=True, exist_ok=True)
    body_dir.mkdir(parents=True, exist_ok=True)
    for source_file in endpoint_dir.glob("*.rs"):
        source_file.unlink()
    for source_file in body_dir.glob("*.rs"):
        source_file.unlink()
    (source_dir / "lib.rs").write_text(crate_root, encoding="utf-8")
    (source_dir / "prepared.rs").write_text(prepared_root, encoding="utf-8")
    for name, source in (extra_source_files or {}).items():
        (source_dir / name).write_text(source, encoding="utf-8")
    (prepared_dir / "endpoints.rs").write_text(
        endpoint_definitions + endpoint_modules,
        encoding="utf-8",
    )
    if write_endpoint_module:
        (endpoint_dir / "test.rs").write_text(endpoints, encoding="utf-8")
    else:
        (endpoint_dir / "test.rs").unlink(missing_ok=True)
    for name, source in (extra_endpoint_files or {}).items():
        (endpoint_dir / name).write_text(source, encoding="utf-8")
    (prepared_dir / "bodies.rs").write_text(
        body_definitions + body_modules,
        encoding="utf-8",
    )
    (body_dir / "test.rs").write_text(bodies, encoding="utf-8")
    return subprocess.run(
        [
            str(CHECKER),
            "--matrix",
            str(matrix),
            "--manifest",
            str(directory / "Cargo.toml"),
            "--endpoints",
            str(endpoint_dir),
            "--bodies",
            str(body_dir),
            "--body-lock",
            str(body_lock),
            "--expected-active",
            "2",
            "--expected-bodies",
            "1",
        ],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
